// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.0
// source: cmdb/apps/secret/pb/model.proto

package secret

import (
	resource "github.com/GeekQk/devcloud-mini/cmdb/apps/resource"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Type int32

const (
	Type_API_KEY       Type = 0
	Type_USER_PASSWORD Type = 1
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0: "API_KEY",
		1: "USER_PASSWORD",
	}
	Type_value = map[string]int32{
		"API_KEY":       0,
		"USER_PASSWORD": 1,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_cmdb_apps_secret_pb_model_proto_enumTypes[0].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_cmdb_apps_secret_pb_model_proto_enumTypes[0]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type.Descriptor instead.
func (Type) EnumDescriptor() ([]byte, []int) {
	return file_cmdb_apps_secret_pb_model_proto_rawDescGZIP(), []int{0}
}

type Secret struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// secret id
	// @gotags: json:"id" bson:"_id"
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id" bson:"_id"`
	// secret id
	// @gotags: json:"domain" bson:"domain"
	Domain string `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain" bson:"domain"`
	// secret id
	// @gotags: json:"namespace" bson:"namespace"
	Namespace string `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace" bson:"namespace"`
	// 创建secret的请求
	Spec *CreateSecretRequest `protobuf:"bytes,4,opt,name=spec,proto3" json:"spec,omitempty"`
}

func (x *Secret) Reset() {
	*x = Secret{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmdb_apps_secret_pb_model_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Secret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Secret) ProtoMessage() {}

func (x *Secret) ProtoReflect() protoreflect.Message {
	mi := &file_cmdb_apps_secret_pb_model_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Secret.ProtoReflect.Descriptor instead.
func (*Secret) Descriptor() ([]byte, []int) {
	return file_cmdb_apps_secret_pb_model_proto_rawDescGZIP(), []int{0}
}

func (x *Secret) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Secret) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Secret) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Secret) GetSpec() *CreateSecretRequest {
	if x != nil {
		return x.Spec
	}
	return nil
}

type CreateSecretRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 凭证的类型
	// @gotags: json:"type"
	Type Type `protobuf:"varint,1,opt,name=type,proto3,enum=qk.cmdb.secret.Type" json:"type"`
	// @gotags: json:"key" validate:"required"
	Key string `protobuf:"bytes,2,opt,name=key,proto3" json:"key" validate:"required"`
	// @gotags: json:"value" validate:"required"
	Value string `protobuf:"bytes,3,opt,name=value,proto3" json:"value" validate:"required"`
	// 允许同步的资源的Region列表
	// @gotags: json:"regions"
	Regions []string `protobuf:"bytes,4,rep,name=regions,proto3" json:"regions"`
	// 允许同步的资源的类型
	// @gotags: json:"resource_types"
	ResourceTypes []resource.TYPE `protobuf:"varint,5,rep,packed,name=resource_types,json=resourceTypes,proto3,enum=qk.cmdb.resource.TYPE" json:"resource_types"`
}

func (x *CreateSecretRequest) Reset() {
	*x = CreateSecretRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cmdb_apps_secret_pb_model_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSecretRequest) ProtoMessage() {}

func (x *CreateSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmdb_apps_secret_pb_model_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSecretRequest.ProtoReflect.Descriptor instead.
func (*CreateSecretRequest) Descriptor() ([]byte, []int) {
	return file_cmdb_apps_secret_pb_model_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSecretRequest) GetType() Type {
	if x != nil {
		return x.Type
	}
	return Type_API_KEY
}

func (x *CreateSecretRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CreateSecretRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *CreateSecretRequest) GetRegions() []string {
	if x != nil {
		return x.Regions
	}
	return nil
}

func (x *CreateSecretRequest) GetResourceTypes() []resource.TYPE {
	if x != nil {
		return x.ResourceTypes
	}
	return nil
}

var File_cmdb_apps_secret_pb_model_proto protoreflect.FileDescriptor

var file_cmdb_apps_secret_pb_model_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x63, 0x6d, 0x64, 0x62, 0x2f, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x73, 0x65, 0x63, 0x72,
	0x65, 0x74, 0x2f, 0x70, 0x62, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0e, 0x71, 0x6b, 0x2e, 0x63, 0x6d, 0x64, 0x62, 0x2e, 0x73, 0x65, 0x63, 0x72, 0x65,
	0x74, 0x1a, 0x21, 0x63, 0x6d, 0x64, 0x62, 0x2f, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x72, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x2f, 0x70, 0x62, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x87, 0x01, 0x0a, 0x06, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x37, 0x0a, 0x04, 0x73, 0x70, 0x65, 0x63, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x71, 0x6b, 0x2e, 0x63, 0x6d, 0x64, 0x62, 0x2e, 0x73, 0x65,
	0x63, 0x72, 0x65, 0x74, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x65, 0x63, 0x72, 0x65,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x04, 0x73, 0x70, 0x65, 0x63, 0x22, 0xc0,
	0x01, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x71, 0x6b, 0x2e, 0x63, 0x6d, 0x64, 0x62, 0x2e, 0x73,
	0x65, 0x63, 0x72, 0x65, 0x74, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x67, 0x69,
	0x6f, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x72, 0x65, 0x67, 0x69, 0x6f,
	0x6e, 0x73, 0x12, 0x3d, 0x0a, 0x0e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x71, 0x6b, 0x2e,
	0x63, 0x6d, 0x64, 0x62, 0x2e, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x54, 0x59,
	0x50, 0x45, 0x52, 0x0d, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x73, 0x2a, 0x26, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x41, 0x50, 0x49,
	0x5f, 0x4b, 0x45, 0x59, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x50,
	0x41, 0x53, 0x53, 0x57, 0x4f, 0x52, 0x44, 0x10, 0x01, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x47, 0x65, 0x65, 0x6b, 0x51, 0x6b, 0x2f, 0x64,
	0x65, 0x76, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2d, 0x6d, 0x69, 0x6e, 0x69, 0x2f, 0x63, 0x6d, 0x64,
	0x62, 0x2f, 0x61, 0x70, 0x70, 0x73, 0x2f, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cmdb_apps_secret_pb_model_proto_rawDescOnce sync.Once
	file_cmdb_apps_secret_pb_model_proto_rawDescData = file_cmdb_apps_secret_pb_model_proto_rawDesc
)

func file_cmdb_apps_secret_pb_model_proto_rawDescGZIP() []byte {
	file_cmdb_apps_secret_pb_model_proto_rawDescOnce.Do(func() {
		file_cmdb_apps_secret_pb_model_proto_rawDescData = protoimpl.X.CompressGZIP(file_cmdb_apps_secret_pb_model_proto_rawDescData)
	})
	return file_cmdb_apps_secret_pb_model_proto_rawDescData
}

var file_cmdb_apps_secret_pb_model_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cmdb_apps_secret_pb_model_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cmdb_apps_secret_pb_model_proto_goTypes = []interface{}{
	(Type)(0),                   // 0: qk.cmdb.secret.Type
	(*Secret)(nil),              // 1: qk.cmdb.secret.Secret
	(*CreateSecretRequest)(nil), // 2: qk.cmdb.secret.CreateSecretRequest
	(resource.TYPE)(0),          // 3: qk.cmdb.resource.TYPE
}
var file_cmdb_apps_secret_pb_model_proto_depIdxs = []int32{
	2, // 0: qk.cmdb.secret.Secret.spec:type_name -> qk.cmdb.secret.CreateSecretRequest
	0, // 1: qk.cmdb.secret.CreateSecretRequest.type:type_name -> qk.cmdb.secret.Type
	3, // 2: qk.cmdb.secret.CreateSecretRequest.resource_types:type_name -> qk.cmdb.resource.TYPE
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_cmdb_apps_secret_pb_model_proto_init() }
func file_cmdb_apps_secret_pb_model_proto_init() {
	if File_cmdb_apps_secret_pb_model_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cmdb_apps_secret_pb_model_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Secret); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cmdb_apps_secret_pb_model_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSecretRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cmdb_apps_secret_pb_model_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cmdb_apps_secret_pb_model_proto_goTypes,
		DependencyIndexes: file_cmdb_apps_secret_pb_model_proto_depIdxs,
		EnumInfos:         file_cmdb_apps_secret_pb_model_proto_enumTypes,
		MessageInfos:      file_cmdb_apps_secret_pb_model_proto_msgTypes,
	}.Build()
	File_cmdb_apps_secret_pb_model_proto = out.File
	file_cmdb_apps_secret_pb_model_proto_rawDesc = nil
	file_cmdb_apps_secret_pb_model_proto_goTypes = nil
	file_cmdb_apps_secret_pb_model_proto_depIdxs = nil
}
