[app]
  name = "mcenter"

[http]
  # HTTP服务端口
  port = 7080

[grpc]
  # Server监听的端口
  port = 17080


[mongodb]
  endpoints = ["dds-8vb5e579cddbaaa41100-pub.mongodb.zhangbei.rds.aliyuncs.com:3717"]
  database = "zdb"
  username = "root"
  password = "qiKAI!!395166"


[apidoc]
  # Swagger API Doc URL路径, 默认自动生成带前缀的地址比如: /default/api/v1/apidoc 
  # 你也可以在这里直接配置绝对路径 比如: /apidocs.json
  path = "/apidocs.json"


[trace]
  enable = false
  provider = "otlp"
  endpoint = "127.0.0.1:4318"
  insecure = true